#!/bin/bash
# Installation script for TakeCare Childcare Website

echo "========================================="
echo "TakeCare Childcare Website - Setup"
echo "========================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if MySQL is installed
if ! command -v mysql &> /dev/null; then
    echo -e "${RED}Error: MySQL is not installed or not in PATH${NC}"
    exit 1
fi

echo -e "${GREEN}✓ MySQL found${NC}"
echo ""

# Get database credentials
echo "Please enter your MySQL credentials:"
read -p "MySQL Host [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-localhost}

read -p "MySQL User [root]: " DB_USER
DB_USER=${DB_USER:-root}

read -sp "MySQL Password: " DB_PASS
echo ""

read -p "Database Name [childcare_website]: " DB_NAME
DB_NAME=${DB_NAME:-childcare_website}

echo ""
echo "Testing MySQL connection..."

# Test connection
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" -e "SELECT 1;" &> /dev/null; then
    echo -e "${GREEN}✓ Connection successful${NC}"
else
    echo -e "${RED}✗ Connection failed. Please check your credentials.${NC}"
    exit 1
fi

echo ""
echo "Importing database schema..."

# Import schema
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" < db/schema.sql; then
    echo -e "${GREEN}✓ Database schema imported successfully${NC}"
else
    echo -e "${RED}✗ Failed to import schema${NC}"
    exit 1
fi

echo ""
echo "Updating config/db.php with your credentials..."

# Update config file
cat > config/db.php << EOF
<?php
// config/db.php
// Database configuration - Auto-generated by install.sh
\$host = '$DB_HOST';
\$db   = '$DB_NAME';
\$user = '$DB_USER';
\$pass = '$DB_PASS';
\$charset = 'utf8mb4';

\$dsn = "mysql:host=\$host;dbname=\$db;charset=\$charset";
\$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);
} catch (PDOException \$e) {
    // Fallback: if there's a legacy mysqli config at db/db.php, include it so pages still load.
    if (file_exists(__DIR__ . '/../db/db.php')) {
        require_once __DIR__ . '/../db/db.php';
        // \$conn (mysqli) will be available from that file.
    } else {
        // Show a friendly error for debugging; in production log this instead.
        die('Database connection failed: ' . \$e->getMessage());
    }
}
EOF

echo -e "${GREEN}✓ Configuration updated${NC}"

echo ""
echo "Creating uploads directory..."

# Create uploads directory
mkdir -p uploads/gallery
chmod 775 uploads/gallery

echo -e "${GREEN}✓ Uploads directory created${NC}"

echo ""
echo "========================================="
echo -e "${GREEN}Installation completed successfully!${NC}"
echo "========================================="
echo ""
echo "Default admin credentials:"
echo "  Email: admin@gardekids.com"
echo "  Password: admin123"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: Please change the admin password after first login!${NC}"
echo ""
echo "Access your site:"
echo "  Frontend: http://your-domain/takecare/"
echo "  Admin Panel: http://your-domain/takecare/admin/"
echo ""
echo "Next steps:"
echo "  1. Visit your website"
echo "  2. Login to admin panel"
echo "  3. Change admin password"
echo "  4. Add testimonials and gallery images"
echo "  5. Customize contact information"
echo ""
echo "For more information, see README.md"
echo ""
